export const LOGIN = 'LOGIN'
export const IS_USER_LOGGEDIN = 'IS_USER_LOGGEDIN'
export const REGISTER = 'REGISTER'
export const SIGNOUT = 'SIGNOUT'
export const SEND_PASSWORD_RESET_EMAIL = 'SEND_PASSWORD_RESET_EMAIL'
export const CONFIRM_PASSWORD_RESET = 'CONFIRM_PASSWORD_RESET'
export const VERIFY_PASSWORD_RESET_CODE = 'VERIFY_PASSWORD_RESET_CODE'

//current tracking time entry item
export const TIME_ENTRY_INPUT__PULL = 'TIME_ENTRY_INPUT__PULL'
export const TIME_ENTRY_INPUT__START = 'TIME_ENTRY_INPUT__START'
export const TIME_ENTRY_INPUT__STOP = 'TIME_ENTRY_INPUT__STOP'
export const TIME_ENTRY_INPUT__CHANGE_START_TIME = 'TIME_ENTRY_INPUT__CHANGE_START_TIME'
export const TIME_ENTRY_INPUT__CHANGE_TEXT = 'TIME_ENTRY_INPUT__CHANGE_TEXT'
